import os

""" 
Renames the filenames within the same directory to be Unix friendly
(1) Changes spaces to hyphens
(2) Makes lowercase (not a Unix requirement, just looks better ;)

Usage:
python rename.py
"""
#monuments = ['The Statue of Liberty in New York','The Eiffel Tower in Paris','St. Basil’s Cathedral in Moscow','Blue Domed Church in Santorini','The Great Sphinx at Giza','The Pyramids of Giza','The Little Mermaid in Copenhagen','Neptune and the Palace of Versailles','Windmills at Kinderdijk','The Great Chinese Wall in China','The Taj Mahal in Agra','Machu Picchu in Peru','Big Ben in London','The Burj al Arab Hotel','Tower of Pisa','Christ the Redeemer in Rio de Janeiro','Lascaux in France','Mecca in Saudi Arabia','Loch Ness in Scotland','Mont St. Michel in France','Bran Castle in Transylvania','Agia Sophia in Istanbul','Brandenburg Gate in Berlin','Acropolis of Athens','Sagrada Familia in Barcelona','Uluru in the Northern Territory','Neuschwanstein in Bavaria','Mount Fuji in Japan','Stonehenge in the English county of Wiltshire','Mount Eden crater in New Zealand','Easter Island in the Polynesian Triangle','Capitol Hill in Washington DC','Al Aqsa Mosque in Jerusalem','Niagara Falls at the border of Ontario','Angkor Wat at Cambodia','Manneken Pis in Brussels','Mount Everest',' St. Peter’s  Cathedral at Vatican City','Mount Rushmore in South Dakota','Victoria Falls between Zambia and Zimbabwe','The Grand Canyon in Arizona','Nevado Mismi in Peru','The Great Buddha of Kamakura in Japan','Petra in Jordan','Trevi Fountain in Rome','Auschwitz in Poland','Cape of Good Hope in South Africa','North Cape in Norway','Chichen Itza in Mexico','Inukshuk in Canada','Table Mountain in Cape Town','Golden Gate Bridge in San Francisco','Sydney Opera House in Australia','Parc Guell in Barcelona','Kilimanjaro in Tanzania','Forbidden City in Beijing','Iguazu Falls on the border of Brazil and Argentina','The Colosseum in Rome','Twyfelfontein in Namibia','Tower Bridge in London','The Blue Mosque in Istanbul','The Blue Mosque in Istanbul','The Sphinx in Bucegi','Millau Bridge in France','Luxor Temple in Egypt','Dom in Berlin','Faisal Mosque in Islamabad',' Kremlin in Moscow','The Empire State Building in New York','Hermitage in Saint Petersburg','Newgrange in Ireland','Waterloo in Belgium','Carnac in France','Tilicho Lake in Nepal','Temple of Besakih in Bali','Pompeii in Italy','The Wailing Wall in Jerusalem',' Konark Sun Temple in India','Abu Simbel in Egypt','Middle of the Earth in Ecuador','The Prophet’s Mosque in Medina','Jin Mao and SWFC in Shanghai','Sacré Coeur in Paris','American Cemetery in Normandy','Potala Palace in Llasa','Skellig Michael near the coast of Ireland','Angel Falls in Venezuela','The Louvre in Paris','Atomium in Brussels','White Cliffs of Dover in Great Britain','Minaret of Jam in Afghanistan','Golden Temple  of Amritsar in India','The Palace of Parliament in Bucharest','Rock of Gibraltar','Lotus Temple in New Delhi','Half Dome at Yosemite Valley in California','CN Tower in Canada','Hollywood Sign in Los Angeles','Ephesus in Turkey','Twelve Apostles in Australia','Piazza San Marco in Venice','Vinson Massif in Antarctic']

#for i in monuments:
path =  os.getcwd()
filenames = os.listdir(path)
for filename in filenames:
	os.rename(filename, filename.replace(" ", "-").lower())